### PR TITLE
Bands Structure jupyter notebook:

### PR DESCRIPTION
**Pull request by borellim**
- adapt to aiida 1.0b3 and to latest aiida-quantumespresso;
- update the description text.

Note that the `protocol` and `scf_options` inputs are now optional (or at least will be when https://github.com/aiidateam/aiida-quantumespresso/pull/274 is merged), but I chose to use the 'fast' protocol modifier to speed it up a little. It's still very slow though...

Also tell me if you want this directly in master.

### CODE REVIEW

**Comment by borellim** [comment]
Also tell me if you want this directly in master.

**Comment by borellim** [comment]
One other question: should we use the %aiida magic rather than a bunch of imports? It should work with this fix: https://github.com/marvel-nccr/ansible-role-aiidalab/pull/2

**Comment by ltalirz** [comment]
@borellim good to use the %aiida magic.
Is this superseded by #19?

**Comment by d-tomerini** [comment]
@borellim @italirz 
 It is superseeded (simplification in the input section)
But, I did not use %aiida magic, which I will therefore add in my next PR to the aiida-tutorial repository

**Comment by sphuber** [comment]
Superseded by #19

**Pull request closed without merging**
